plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
}

base {
    archivesName = mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    enable {
        version = '21.1.228'
        disableRecompilation = true
    }

    runs {
        client {
            client()
            gameDirectory = project.file('../../run')
        }

        server {
            server()
            gameDirectory = project.file('../../run')
        }
    }

    mods {
        turtlequest {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            mod_id         : mod_id,
            mod_name       : mod_name,
            mod_version    : mod_version,
            mod_group_id   : mod_group_id,
            mod_authors    : mod_authors,
            mod_description: mod_description
    ]

    inputs.properties replaceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

dependencies {
    compileOnly files('../../run/mods/cc-tweaked-1.21.1-forge-1.118.0.jar')
}
