<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Agentica\Agentica\Agentica.csproj" />
    <ProjectReference Include="..\..\..\Agentica\Agentica.Clients\Agentica.Clients.csproj" />
  </ItemGroup>

</Project>
